# cluster-config.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lak-cluster1
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 20
