apiVersion: apps/v1
kind: Deployment
metadata:
  name: lak-aws-eks-test-app-deployment
spec:
  selector:
    matchLabels:
      app: lak-aws-eks-test-app
  template:
    metadata:
      labels:
        app: lak-aws-eks-test-app
    spec:
      containers:
      - name: lak-aws-eks-test-app
        image: narayana2012/lak-aws-eks-test-app
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  name: lak-aws-eks-test-app-service
spec:
  type: LoadBalancer
  selector:
    app: lak-aws-eks-test-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
    
